DbServer:
    address: ecds.doneax.com
    port: 3306
    username: root
    password: AntMysql2015
    name: tmdt
socket_server:
    address: 0.0.0.0
    port: 8866
web_server:
    address: 127.0.0.1
    port: 8849
tmdt:
    #通讯串口
    uart1: com1
